using AINPC.OllamaRuntime;
using AINPC.Tools;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using OllamaSharp;

namespace AINPC;

class MainState : AppState
{
	#region Fields

	private readonly AppSettings _settings;
	private readonly ILogger<MainState> _logger;
	private readonly IServiceProvider _serviceProvider;
	private readonly OllamaRepo _ollamaRepo;

	#endregion

	#region Constructors

	public MainState(IOptions<AppSettings> settings, ILogger<MainState> logger, IServiceProvider serviceProvider, OllamaRepo ollamaRepo)
	{
		_settings = settings?.Value ?? throw new ArgumentNullException(nameof(settings));
		_logger = logger ?? throw new ArgumentNullException(nameof(logger));
		_serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
		_ollamaRepo = ollamaRepo ?? throw new ArgumentNullException(nameof(ollamaRepo));
	}

	#endregion

	#region Methods

	protected override async Task LoadStateAsync()
	{
		Console.WriteLine("AINPC Ollama Test");
		Console.WriteLine("----------------------------------");

		await _ollamaRepo.InitializeAsync();
		await _ollamaRepo.SetModelAsync(_settings.ModelId);

		Console.WriteLine("Ollama server is running.");
	}

	protected override async Task UnloadStateAsync()
	{
		// Stop server cleanly.
		_ollamaRepo.Dispose();
		Console.WriteLine("Server stopped.");
		await Task.CompletedTask;
	}

	public override async Task RunAsync()
	{
		try
		{
			await LoadStateAsync();

			// await _ollamaRepo.ReportInstalledModelsAsync();
			// await _ollamaRepo.ReportRunningModelsAsync();

			// Basic text generation.
			// Console.WriteLine("Testing: `My name is Trey. How are you today?`");
			// var response = await _ollamaRepo.GenerateAsync("How are you today?");
			// Console.WriteLine(response);

			// Interactive chat.
			var systemPrompt = @"You are a helpful assistant.

Your first priority is to use tools when they are relevant.
Only answer from your own knowledge if no tool applies.
If you do not know something, say so.

When the user asks about the weather, ALWAYS call the GetWeather tool. Do not guess the weather.

Keep responses short and direct unless the user requests more detail.
";
			//var systemPrompt = @"You are a helpful assistant.

			// You respond honestly, prioritizing details in order from:
			// 1. tools you have access to,
			// 2. the current conversation,
			// 3. then any pre-existing knowledge on the subject.

			// Do not make anything up.  If you do not know something, let the user know.
			// Don't attempt math or numerical conversions without a tool.
			// No need to be overly verbose in your response unless prompted to do so.  Err on the side of keeping your responses short.
			// Don't give additional details beyond what the user is asking for. 

			// If the user appears to be asking for the weather do not make up a response. Use the GetWeather tool to get the answer.";
			var chat = _ollamaRepo.CreateChat(systemPrompt);

			IEnumerable<object> tools = [
				new GetWeatherTool()
			];

			Console.WriteLine("Beginning interactive chat.");
			while (true)
			{
				Console.Write("You: ");
				var message = Console.ReadLine();
				if (string.IsNullOrWhiteSpace(message))
				{
					break;
				}

				Console.Write("Assistant: ");
				await foreach (var answerToken in chat.SendAsync(message, tools))
				{
					Console.Write(answerToken);
				}

				Console.WriteLine();
			}
		}
		catch (Exception ex)
		{
			_logger.LogError(ex, ex.Message);
			throw;
		}
		finally
		{
			await UnloadStateAsync();
		}
	}

	#endregion
}


// /// <summary>
// /// This class was auto-generated by the OllamaSharp ToolSourceGenerator.
// /// </summary>
// public class GetWeatherTool : OllamaSharp.Models.Chat.Tool, OllamaSharp.Tools.IInvokableTool
// {
// 	/// <summary>
// 	/// Initializes a new instance with metadata about the original method.
// 	/// </summary>
// 	public GetWeatherTool()
// 	{
// 		this.Function = new OllamaSharp.Models.Chat.Function
// 		{
// 			Name = "GetWeather",
// 			Description = "Gets the current weather for a given location."
// 		};

// 		this.Function.Parameters = new OllamaSharp.Models.Chat.Parameters
// 		{
// 			Properties = new Dictionary<string, OllamaSharp.Models.Chat.Property>
// 				{
// 					{ "location", new OllamaSharp.Models.Chat.Property { Type = "string", Description = "The location or city to get the weather for" } },
// 					{ "unit", new OllamaSharp.Models.Chat.Property { Type = "string", Description = "The unit to measure the temperature in", Enum = new[] {"Celsius", "Fahrenheit"} } }
// 				},
// 			Required = new[] { "location", "unit" }
// 		};
// 	}

// 	/// <summary>
// 	/// Invokes the tool with given arguments synchronously
// 	/// </summary>
// 	/// <param name="args">The arguments to invoke the tool with</param>
// 	/// <returns>The result of the invoked tool</returns>
// 	public object? InvokeMethod(IDictionary<string, object?>? args)
// 	{
// 		if (args == null) args = new Dictionary<string, object?>();
// 		string location = (string?)args["location"] ?? "";
// 		Unit unit = (Unit)Enum.Parse(typeof(Unit), args["unit"]?.ToString() ?? "", ignoreCase: true);

// 		var result = GetWeather(location, unit);
// 		return result;
// 	}

// 	public static string GetWeather(string location, Unit unit)
// 	{
// 		return unit switch
// 		{
// 			Unit.Fahrenheit => $"It's cold at only 3.14159° {unit} in {location}.",
// 			Unit.Celsius => $"It's warm at only 23 degrees {unit} in {location}, but is {location} a real place?",
// 			_ => "I don't really know.",
// 		};
// 	}
// }